### ISSUE TITLE
Remove hardcoded dependency on appsettings

### ISSUE THREAD

**Issue by redsquare** [logentries/le_nlog#12]
When running on azure we need to read config settings using the cloud config manager which first looks in the azure cloud settings and fallsback to web config. At present the le c# target auto looks in web/app config. Can we change this so we can override or set which config manager to use?

http://msdn.microsoft.com/en-us/LIBRARY/microsoft.windowsazure.cloudconfigurationmanager

**Comment by gearoidof** [comment]
Hi redsquare

This library is no longer maintained by logentries, we'd recommend using our .Net library here: https://github.com/logentries/le_dotnet
