### ISSUE TITLE
Nlog assembly issue

### ISSUE THREAD

**Issue by ddisys** [logentries/le_nlog#13]
We have the latest version 4.2.3.1371 installed. Modified the config files accordingly. 
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />      
        <bindingRedirect oldVersion="0.0.0.0-4.2.3.1371" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>

Also have specific version turned on for Nlog and logentries.Nlog and logentries.Core. When we try to install, we get the following error.

![logging](https://cloud.githubusercontent.com/assets/17656065/13540865/fd50aa12-e226-11e5-8a39-0d4b7356f135.png)

I have no idea where this version 3.2.1.0 is coming up from. The machine does not seem to have nlog dll installed at all. It will be great if some one can help with this.

Thanks
Sowmya

**Comment by gearoidof** [comment]
Hi Sowmya,

This library is no longer maintained by logentries, we'd recommend using our .Net library here: https://github.com/logentries/le_dotnet
